fix: thread leak
hashgraph/hedera-sdk-java pull request #1091
Opened 2022-08-15 22:31 UTC by Sean-Tedrow-LB

Signed-off-by: Sean Tedrow <sean.tedrow@launchbadge.com>

**Related issue(s)**:

Fixes #1084

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

2022-08-15 22:47 UTC, danielakhterov commented
cc @steven-sheehy

2022-08-15 22:49 UTC, steven-sheehy requested changes

2022-08-15 22:49 UTC, steven-sheehy commented on sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
> +            executor.shutdown();
Doesn't fix a similar problem in `close(Duration)`. Should combine the two implementations so that one calls the other with a default timeout.

2022-08-15 22:49 UTC, steven-sheehy commented on sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
> +                if (!executor.awaitTermination(60, TimeUnit.SECONDS)) {
Waiting up until 90 seconds by default is a bit long. After combining the two methods should set a reasonable overall timeout like 30s and decrement time spent between the two `awaitTermination()` methods.

2022-08-15 22:49 UTC, steven-sheehy commented on sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
>              throw new RuntimeException(e);
Shouldn't rethrow `InterruptedException`. Call `Thread.currentThread().interrupt()` instead.

2022-08-15 22:49 UTC, danielakhterov commented on sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
> +            if (!executor.awaitTermination(30, TimeUnit.SECONDS)) {
Should we be using `closeTimeout` here?

2022-08-22 23:24 UTC, danielakhterov approved these changes

2022-08-23 00:07 UTC, steven-sheehy approved these changes

2022-08-23 02:05 UTC, merged

2022-10-07 19:09 UTC, Sean-Tedrow-LB commented on sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
> +        return ForkJoinPool.commonPool();
@limechain

Revert this change, keep the rest of the changes in this PR.

2022-10-07 19:16 UTC, Sean-Tedrow-LB commented on sdk/src/main/java/com/hedera/hashgraph/sdk/Client.java
> +
@limechain

Close the executor here