Example HIP-542 #1170
hashgraph/hedera-sdk-java pull request #1204
Opened 2022-10-25 13:01 UTC by nikola-genov

**Description**:
This PR adds example for HIP 542 - Account create with HTS

**Related issue(s)**:

Fixes #1170

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-10-25 14:37 UTC, ochikov approved these changes

2022-10-26 10:52 UTC, dikel requested changes

2022-10-26 10:52 UTC, dikel commented on examples/src/main/java/AccountCreateWithHtsExample.java
> +        if (nftOwnerAccountId == accountId)
We should use .equals() instead of "=="

2022-10-26 11:17 UTC, dikel approved these changes

2022-10-26 11:26 UTC, merged