Feat: support account alias keys
hashgraph/hedera-sdk-java pull request #799
Opened 2021-12-10 05:56 UTC by Sean-Tedrow-LB

**Description**:

Add support for [HIP-32](https://hips.hedera.com/hip/hip-32)

**Related issue(s)**:

Fixes #791

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-12-13 23:05 UTC, danielakhterov requested changes

2021-12-13 23:05 UTC, danielakhterov commented on sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionRecord.java
> +            transactionRecord.setAlias(ByteString.copyFrom(aliasKey.toBytes()));
```suggestion
            transactionRecord.setAlias(aliasKey.toProtobufKey().toByteString());
```

2021-12-13 23:05 UTC, danielakhterov commented on sdk/src/main/java/com/hedera/hashgraph/sdk/AccountId.java
> +            return "" + shard + "." + realm + "." + aliasKey.toStringDER();
Should probably error here instead of serializing just like `toString()`.

2021-12-15 20:13 UTC, SimiHunjan commented on sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionReceiptQuery.java
> +    public TransactionReceiptQuery setIncludeChildren(boolean value) {
add comments for `setIncludeChildren`, `setIncludeDuplicates`, etc

2021-12-15 23:44 UTC, SimiHunjan commented on sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionRecord.java
> +        List<TransactionRecord> children
Is this representing the parent consensus timestamp? I didn't see a children field being returned in the protobuf here: https://github.com/hashgraph/hedera-protobufs/blob/v0.21.0/services/transaction_record.proto

2021-12-16 00:01 UTC, SimiHunjan commented on sdk/src/main/java/com/hedera/hashgraph/sdk/TransactionRecord.java
> +        List<TransactionRecord> children
understand why children is there now. Please add parent consensus timestamp.

2021-12-17 21:46 UTC, danielakhterov approved these changes

2021-12-17 21:46 UTC, merged