implement #818 [Private|Public]Key.is[ED25519|ECDSA]()
hashgraph/hedera-sdk-java pull request #883
Opened 2022-02-17 00:35 UTC by rickyrodmac

Updated
CHANGELOG.md
PrivateKey.java
PrivateKeyECDSA.java
PrivateKeyED25519.java
PublicKey.java
PublicKeyECDSA.java
PublicKeyED25519.java
ECDSAPrivateKeyTest.java
ECDSAPublicKeyTest.java
Ed25519PrivateKeyTest.java
Ed25519PublicKeyTest.java

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-02-21 03:40 UTC, danielakhterov approved these changes

2022-02-21 03:42 UTC, danielakhterov approved these changes
@rickyrodmac Make sure you sign off on all the commits and if you can please regenerate the `AccountIdTest.snap` file; this can be done by simply removing the file and running `./gradlew build` again.

2022-02-22 20:40 UTC, Sean-Tedrow-LB requested changes

2022-02-25 21:24 UTC, rickyrodmac commented on sdk/src/main/java/com/hedera/hashgraph/sdk/PrivateKeyECDSA.java
> +    public boolean isED25519() { return false; }
Done.

2022-02-26 03:06 UTC, merged